# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 1.py
# Created on: 2021-01-21 16:18:50.00000
#   (generated by gaosong)
# Description:批处理掩膜文件
# ---------------------------------------------------------------------------

# coding=utf-8
# 批量处理文件夹内的所有shp数据的坐标转换
import os
import arcpy
import sys

# 待处理影像存放位置
baseFile = r"F:/fuyang_sss/84_50_0"
# 待处理影像存放文件夹名称
inputDirName = '84_50_0'
# 输出文件位置的相对baseFile-inputDirName的路径
# outputDirName = 'Mask/funanxian'
outputDirName = 'Mask/yingzhou'
# 掩膜矢量文件
# mask_shp_file = r"F:/fuyang_sss/Mask/funanxian.shp"
mask_shp_file = r"F:/fuyang_sss/Mask/yingzhou.shp"


def maskRaster(input_file, output_file):
    print('正在处理：', input_file)
    print('输出文件：', output_file)
    # Process: Extract by Mask
    arcpy.gp.ExtractByMask_sa(input_file, mask_shp_file, output_file)
    print('当前文件处理完成')


def oswalk(file_dir):
    print(os.walk(file_dir))
    for root, dirs, files in os.walk(file_dir):
        print(len(files));
        for file in files:
            (filename, extension) = os.path.splitext(file)  # 将文件名拆分为文件名与后缀
            if (extension == '.tif'):
                path_filedir = '/'.join(root.split('\\'))
                path_array = path_filedir.split(inputDirName)
                output_file_name = path_array[0] + outputDirName + path_array[1].decode('gb2312')
                if not os.path.exists(output_file_name):
                    os.mkdir(output_file_name)
                output_file_shp = output_file_name + '/' + file
                input_file_shp = path_filedir.decode('gb2312') + '/' + file
                maskRaster(input_file_shp, output_file_shp)


if __name__ == '__main__':
    oswalk(baseFile)
